plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Type: minecraft
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
  ansible_user: ec2-user
  ansible_ssh_private_key_file: ~/.ssh/minecraft-key